### ISSUE TITLE
TypeError: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by Witsung** [conversationai/conversationai-moderator#12]
Hi, I got into trouble when trying to setup the local mysql. when I run the second commands(for the first line is ok, but not for the second):
mysql -uroot os_moderator < packages/backend-core/seed/initial-database.sql 
./bin/osmod migrate

I got the error message below. Any help is appreciated. 

## Context
conversationai-moderator-master/packages/backend-core/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (./conversationai-moderator-master/packages/backend-core/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (./conversationai-moderator-master/packages/backend-core/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at Object.<anonymous> (./conversationai-moderator-master/packages/backend-core/dist/domain/auth/providers/google.js:91:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./conversationai-moderator-master/packages/backend-core/dist/domain/auth/providers/index.js:21:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by rehat101** [comment]
@Witsung I get the same error when I run the migrate command. Have you find a solution for this yet?
